package com.sparta.w4assignment.error;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
	NOT_FOUND(404,"COMMON-ERR-404","PAGE NOT FOUND"),
	INTER_SERVER_ERROR(500,"COMMON-ERR-500","INTER SERVER ERROR"),
//	UNAUTHENTICATED(401,"AUTHENTICATION-ERR-401","NOT AUTHENTICATED"),// 유저 정보 없이 접근
//	FORBIDDEN(403,"AUTHORIZATION-ERR-403","NOT AUTHORIZED"), // 유저 정보는 있으나 권한 없이
//	INVALID_SIGNATURE_TOKEN(401, "TOKEN-SIGN-ERR-401", "WRONGLY SIGNED TOKEN"), // 잘못된 JWT 서명
//	EXPIRED_TOKEN(401, "TOKEN-EXPIRATION-ERR-401", "EXPIRED TOKEN"), // 만료된 JWT 토큰
//	UNSUPPORTED_TOKEN(401, "TOKEN-SUPPORT-ERR-401", "UNSUPPORTED TOKEN"), // 지원되지 않는 JWT 토큰
//	WRONG_TOKEN(401, "TOKEN-ERR-401", "WRONG TOKEN"), // 잘못된 JWT 토큰
	WRONG_REFRESH_TOKEN(401,"REFRESH-TOKEN-ERR-401","WRONG REFRESH TOKEN"), // 잘못된 Refresh Token
//	NOT401(401, "SECURITY-CONTEXT-ERR-401", "NO AUTHENTICATION INFORMATION"), // Security Context 에 인증 정보 없음
	NOT_FOUND_USERID(401, "USER-ID-ERR-401", "NOT FOUND USERID"), // 해당 userId 없음
	NOT_FOUND_POST(401,"POST-ERR-401","NOT FOUND POST"), // 해당 포스트 없음
	NOT_FOUND_COMMENT(401, "COMMENT-ERR-401", "NOT FOUND COMMENT"),
	LOGGED_OUT_USER(401,"USER-LOGOUT-401","LOGGED OUT USER"), // 로그아웃된 사용자
	MISMATCHED_TOKEN(401,"MISMATCHED-TOKEN-401","TOKEN USER MISMATCH"), // Refresh Token 과 해당 유저의 Refresh Token 불일치
	NOT_FOUND_USER(401, "USER-ERR-401", "NOT FOUND USER"), // 해당 유저 없음
	NOT_FOUND_ME(401, "MY-USER-ERR-401", "NOT FOUND MY"),// 로그인 유저 정보 없음 (Security Context)
	ID_DUPLICATION(401, "USER-SIGNUP-ID-ERR-401", "ID DUPLICATED"), // 중복된 userId
	ADMIN_TOKEN_MISMATCHED(401, "USER-SIGNUP-ROLE-ERR-401", "ADMIN TOKEN MISMATCHED"), // 관리자 토큰 불일치

	;
	private final int status;
	private final String errorCode;
	private final String message;
}